defaults:
  - compare_schema
  - environment@simulation.environment: default
  - population@simulation.population: schema
  - individual@simulation.individual: schema
  - fitness@simulation.fitness: schema
  - _self_

retrain_steps: 50
shift_strength: 0.7
x_trait: heat_resistance
y_trait: cold_resistance
view: false

hydra:
  run:
    dir: artifacts/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: artifacts/hydra/multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false
