defaults:
  - sim_schema
  - environment: default
  - population: schema
  - individual: schema
  - fitness: schema
  - _self_

n_steps: 600
seed: 42
steps_info: 5
model_info: false
population_info: false
individual_info: false
view: false
debug: false

hydra:
  job:
    chdir: false
