defaults:
  - sim_schema
  - environment: default
  - population: schema
  - individual: schema
  - fitness: schema
  - _self_

n_steps: 600
seed: 42
steps_info: 5
model_info: false
population_info: false
individual_info: false
view: false
debug: false

hydra:
  run:
    dir: artifacts/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: artifacts/hydra/multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false
